blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/miikkak/mc-server-container/discussions
    about: Please use GitHub Discussions for questions and general discussions
